version: '3.8'

services:
  app:
    build: .
    image: docker-socket-lab
    container_name: socket-test
    stdin_open: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: /bin/bash
